---
- name: 1.4.1 Set User/Group Owner on /etc/grub.conf (Scored)
  file:
    path=/boot/grub/grub.conf
    owner=root
    group=root
    mode=0600
  tags:
    - scored
    - section1.4
    - section1.4.1
  when: ansible_distribution_major_version == '6'


- name: 1.4.1 Set User/Group Owner on /etc/grub.conf (Scored)
  file:
    path=/boot/grub2/grub.cfg
    owner=root
    group=root
  tags:
    - scored
    - section1.4
    - section1.4.1
  when: ansible_distribution_major_version == '7'

- name: 1.4.2 Set boot loader password (Scored)
  debug: msg="*** Too destructive for production systems. Evaluate for your environment first. Not relevant for public cloud."
  tags:
    - scored
    - section1.4
    - section1.4.2

- name: 1.4.3 Require authentication for single-user mode (Scored)
  debug: msg="*** Too destructive for production systems. Evaluate for your environment first. Not relevant for public cloud."
  tags:
    - scored
    - section1.4
    - section1.4.3

