---
  - name: 5.5 Restrict root login to system console (Not Scored)
    # (clear contents of /etc/securetty)
    copy: >
      content=""
      dest=/etc/securetty
      mode=0400
    tags:
      - notscored
      - section5.5

  - name: 5.6 Restrict Access to the su Command (Scored)
    copy: >
      src=etc/pam.d/su
      dest=/etc/pam.d/su
    tags:
      - scored
      - section5.6
