---
- name: Create /etc/modprobe.d/CIS.conf with root ownership & mode
  file: path=/etc/modprobe.d/CIS.conf state=touch owner=root group=root mode=0600
  changed_when: false
  tags:
    - notscored
    - section1.1
    - section1.1.1
    - section1.1.1.1
    - section1.1.1.2
    - section1.1.1.3
    - section1.1.1.4
    - section1.1.1.5
    - section1.1.1.6
    - section1.1.1.7
    - section1.1.1.8

- name: 1.1.1.1 Disable Mounting of cramfs Filesystems (Not Scored)
  lineinfile: >
    state=present
    dest=/etc/modprobe.d/CIS.conf
    line="install cramfs /bin/true"
  tags:
    - notscored
    - section1.1
    - section1.1.1
    - section1.1.1.1

- name: 1.1.1.2 Disable Mounting of freevxfs Filesystems (Not Scored)
  lineinfile: >
    state=present
    dest=/etc/modprobe.d/CIS.conf
    line="install freevxfs /bin/true"
  tags:
    - notscored
    - section1.1
    - section1.1.1
    - section1.1.1.2

- name: 1.1.1.3 Disable Mounting of jffs2 Filesystems (Not Scored)
  lineinfile: >
    state=present
    dest=/etc/modprobe.d/CIS.conf
    line="install jffs2 /bin/true"
  tags:
    - notscored
    - section1.1
    - section1.1.1
    - section1.1.1.3

- name: 1.1.1.4 Disable Mounting of hfs Filesystems (Not Scored)
  lineinfile: >
    state=present
    dest=/etc/modprobe.d/CIS.conf
    line="install hfs /bin/true"
  tags:
    - notscored
    - section1.1
    - section1.1.1
    - section1.1.1.4

- name: 1.1.1.5 Disable Mounting of hfsplus Filesystems (Not Scored)
  lineinfile: >
    state=present
    dest=/etc/modprobe.d/CIS.conf
    line="install hfsplus /bin/true"
  tags:
    - notscored
    - section1.1
    - section1.1.1
    - section1.1.1.5

- name: 1.1.1.6 Disable Mounting of squashfs Filesystems (Not Scored)
  lineinfile: >
    state=present
    dest=/etc/modprobe.d/CIS.conf
    line="install squashfs /bin/true"
  tags:
    - notscored
    - section1.1
    - section1.1.1
    - section1.1.1.6

- name: 1.1.1.7 Disable Mounting of udf Filesystems (Not Scored)
  lineinfile: >
    state=present
    dest=/etc/modprobe.d/CIS.conf
    line="install udf /bin/true"
  tags:
    - notscored
    - section1.1
    - section1.1.1
    - section1.1.1.7

- name: 1.1.1.8 Disable Mounting of FAT Filesystems (Not Scored)
  lineinfile: >
    state=present
    dest=/etc/modprobe.d/CIS.conf
    line="install vfat /bin/true"
  tags:
    - notscored
    - section1.1
    - section1.1.1
    - section1.1.1.8

- name: 1.1.2 Create Separate Partition for /tmp (Scored)
  shell: 'grep "[[:space:]]/tmp[[:space:]]" /etc/fstab && touch /tmp/.cis-1.1.2'
  args:
    creates: "/tmp/.cis-1.1.2"
  tags:
    - scored
    - section1.1
    - section1.1.2

- name: 1.1.3 Create SystemD Config for /tmp (Scored)
  copy: >
    src="etc/systemd/tmp.mount"
    dest="/etc/systemd/system/tmp.mount"
  tags:
    - scored
    - section1.1
    - section1.1.3
 
- name: 1.1.3 - 1.1.5 Set nodev,nosuid,noexec option for /tmp Partition (Scored)
  mount: >
    name="/tmp"
    src={{ item.device }}
    state=mounted
    fstype={{ item.fstype }}
    opts="nodev,nosuid,noexec"
  when: item.mount == "/tmp"
  with_items: "{{  ansible_mounts }}"
  tags:
    - scored
    - section1.1
    - section1.1.3
    - section1.1.4
    - section1.1.5

- name: 1.1.6 Create Separate Partition for /var (Scored)
  shell: 'grep "[[:space:]]/var[[:space:]]" /etc/fstab && touch /tmp/.cis-1.1.6'
  args:
    creates: "/tmp/.cis-1.1.6"
  tags:
    - scored
    - section1.1
    - section1.1.6

- name: 1.1.7-10 Bind Mount the /var/tmp directory to /tmp (Scored)
  # TODO: this is a bit of cheat, and should be a separate mount point
  mount: >
    name="/var/tmp"
    src="/tmp"
    state=mounted
    fstype="none"
    opts="bind"
  when: item.mount == "/tmp"
  with_items: "{{ ansible_mounts }}"
  tags:
    - scored
    - section1.1
    - section1.1.7
    - section1.1.8
    - section1.1.9
    - section1.1.10

- name: 1.1.11 Create Separate Partition for /var/log (Scored)
  shell: 'grep "[[:space:]]/var/log[[:space:]]" /etc/fstab && touch /tmp/.cis-1.1.11'
  args:
    creates: "/tmp/.cis-1.1.11"
  tags:
    - scored
    - section1.1
    - section1.1.11

- name: 1.1.12 Create Separate Partition for /var/log/audit (Scored)
  shell: 'grep "[[:space:]]/var/log/audit[[:space:]]" /etc/fstab && touch /tmp/.cis-1.1.12'
  args:
    creates: "/tmp/.cis-1.1.12"
  tags:
    - scored
    - section1.1
    - section1.1.12

- name: 1.1.13 Create Separate Partition for /home (Scored)
  shell: 'grep "[[:space:]]/home[[:space:]]" /etc/fstab && touch /tmp/.cis-1.1.13'
  args:
    creates: "/tmp/.cis-1.1.13"
  tags:
    - scored
    - section1.1
    - section1.1.13

- name: 1.1.14 Add nodev Option to /home Partition (Scored)
  mount: >
    name="/home"
    src={{ item.device }}
    state=mounted
    fstype={{ item.fstype }}
    opts="nodev"
  when: item.mount == "/home"
  with_items: "{{ ansible_mounts }} "
  tags:
    - scored
    - section1.1
    - section1.1.14

- name: 1.1.15 - 1.1.17 Add noexec Option to /dev/shm Partition (Scored)
  mount: >
    name="/dev/shm"
    src="none"
    state=mounted
    fstype="tmpfs"
    opts="nodev,nosuid,noexec"
  tags:
    - section1.1
    - section1.1.15
    - section1.1.16
    - section1.1.17
    - scored

- name: 1.1.18 Add nodev Option to Removable Media Partitions (Not Scored)
  debug: msg="*** Not relevant."
  tags:
    - scored
    - section1.1
    - section1.1.18

- name: 1.1.19 Add nosuid Option to Removable Media Partitions (Not Scored)
  debug: msg="*** Not relevant."
  tags:
    - notscored
    - section1.1
    - section1.1.19

- name: 1.1.20 Add noexec Option to Removable Media Partitions (Not Scored)
  debug: msg="*** Not relevant."
  tags:
    - notscored
    - section1.1
    - section1.1.20

- name: 1.1.21 Set sticky bit on all world-writeable directories (Scored)
  shell: "df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type d \\( -perm -0002 -a ! -perm -1000 \\) 2>/dev/null | wc -l | grep 0 && touch /tmp/.cis-1.1.21"
  args:
    creates: "/tmp/.cis-1.1.21"
  tags:
    - scored
    - section1.1
    - section1.1.21

- name: 1.1.22 Disable Automounting (Scored)
  yum: >
    name=autofs
    state=removed
  tags:
    - scored
    - section1.1
    - section1.1.22
