---
#
# Copyright 2014 Major Hayden
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#

  - name: 1.7.1 Set Warning Banner for Standard Login Services (Scored)
    stat: path=/etc/{{ item }}
    register: stats
    with_items:
      - motd
      - issue
      - issue.net
    tags:
      - scored
      - section1.7
      - section1.7.1
      - section1.7.1.1
      - section1.7.1.2
      - section1.7.1.3

  - name: 1.7.1.1 Ensure message of the day is configured properly (Scored)
    file: >
      name=/etc/motd 
      state=absent
    changed_when: false
    with_items: 
      - stats.results
    when: item.islnk is defined
    tags:
      - scored
      - section1.7
      - section1.7.1
      - section1.7.1.1

  - name: 1.7.1.2 Ensure local login warning banner is configured properly (Not Scored)
    file: >
      name=/etc/issue
      state=absent
    changed_when: false
    with_items: 
      - stats.results
    when: item.islnk is defined
    tags:
      - notscored
      - section1.7
      - section1.7.1
      - section1.7.1.2

  - name: 1.7.1.3 Ensure remote login warning banner is configured properly (Not Scored)
    file: >
      name=/etc/issue.net
      state=absent
    changed_when: false
    with_items: 
      - stats.results
    when: item.islnk is defined
    tags:
      - notscored
      - section1.7
      - section1.7.1
      - section1.7.1.3

  - name: 1.7.1 Set Warning Banner for Standard Login Services (Scored)
    copy: >
      src=etc/{{item}}
      dest=/etc/{{item}}
    with_items:
      - motd
      - issue
      - issue.net
    tags:
      - scored
      - section1.7
      - section1.7.1

  - name: 1.7.1.4-6 Set Warning Banner for Standard Login Services (Scored)
    file: >
      path=/etc/{{ item }}
      owner=root
      group=root
      mode=0644
    with_items:
      - motd
      - issue
      - issue.net
    tags:
      - scored
      - section1.7
      - section1.7.1

  - name: 1.7.1 Remove OS Information from Login Warning Banners (Scored)
    replace: >
      dest=/etc/{{ item }}
      regexp='\\\\r|\\\\v|\\\\s' 
      replace='[CIS replaced]'
    with_items:
      - motd
      - issue
      - issue.net 
    tags:
      - scored
      - section1.7
      - section1.7.1

  - name: 1.7.2 Set GNOME Warning Banner (Not Scored)
    debug: msg="*** Not relevant on a non-X11 system"
    tags:
      - scored
      - section1.7
      - section1.7.2
