---
 - name: 5.3.1 Ensure password creation requirements are configured (Scored)
    copy: >
      src=etc/security/pwquality.conf
      dest=/etc/security/pwquality.conf
    tags:
      - scored
      - section5.3
      - section5.3.1

  - name: 5.3.1 - 5.3.4 Configure PAM (Scored)
    copy: >
      src=etc/pam.d/password-auth
      dest=/etc/pam.d/password-auth
    tags:
      - scored
      - section5.3
      - section5.3.1
      - section5.3.2
      - section5.3.3
      - section5.3.4

