---
#
# Copyright 2014 Major Hayden
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
  - name: 9.1.1 Verify System File Permissions (Not Scored)
    command: rpm -Va --nomtime --nosize --nomd5 --nolinkto
    when: verify_permissions
    tags:
      - notscored
      - section9.1
      - section9.1.1

  - name: 9.1.2 Verify Permissions on /etc/passwd (Scored)
    file: >
      path=/etc/passwd
      mode=0644
    tags:
      - scored
      - section9.1
      - section9.1.2

  - name: 9.1.3 Verify Permissions on /etc/shadow (Scored)
    file: >
      path=/etc/shadow
      mode=0000
    tags:
      - scored
      - section9.1
      - section9.1.3

  - name: 9.1.4 Verify Permissions on /etc/gshadow (Scored)
    file: >
      path=/etc/gshadow
      mode=0000
    tags:
      - scored
      - section9.1
      - section9.1.4

  - name: 9.1.5 Verify Permissions on /etc/group (Scored)
    file: >
      path=/etc/group
      mode=0644
    tags:
      - scored
      - section9.1
      - section9.1.5

  - name: 9.1.6 Verify User/Group Ownership on /etc/passwd (Scored)
    file: >
      path=/etc/passwd
      owner=root
      group=root
    tags:
      - scored
      - section9.1
      - section9.1.6

  - name: 9.1.7 Verify User/Group Ownership on /etc/shadow (Scored)
    file: >
      path=/etc/shadow
      owner=root
      group=root
    tags:
      - scored
      - section9.1
      - section9.1.7

  - name: 9.1.8 Verify User/Group Ownership on /etc/gshadow (Scored)
    file: >
      path=/etc/gshadow
      owner=root
      group=root
    tags:
      - scored
      - section9.1
      - section9.1.8

  - name: 9.1.9 Verify User/Group Ownership on /etc/group (Scored)
    file: >
      path=/etc/group
      owner=root
      group=root
    tags:
      - scored
      - section9.1
      - section9.1.9

  - name: 9.1.10 Find World Writable Files (Not Scored)
    shell: "df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type f -perm -0002"
    when: verify_find
    tags:
      - notscored
      - section9.1
      - section9.1.10

  - name: 9.1.11 Find Un-owned Files and Directories (Scored)
    shell: "df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -nouser -ls"
    when: verify_find
    tags:
      - scored
      - section9.1
      - section9.1.11

  - name: 9.1.12 Find Un-grouped Files and Directories (Scored)
    shell: "df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -nogroup -ls"
    when: verify_find
    tags:
      - scored
      - section9.1
      - section9.1.12

  - name: 9.1.13 Find SUID System Executables (Not Scored)
    shell: "for SUID in $(df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}'  sudo find '{}' -xdev -type f -perm -4000 -print); do rpm -V $(rpm -qf ${SUID}); done"
    register: suid
    when: verify_rpm
    tags:
      - notscored
      - section9.1
      - section9.1.13

  - name: 9.1.14 Find SGID System Executables (Not Scored)
    shell: "for SGID in $(df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type f -perm -2000 -print); do rpm -V $(rpm -qf ${SGID}); done"
    register: sgid
    when: verify_rpm
    tags:
      - notscored
      - section9.1
      - section9.1.14

  - name: 9.2.1 Ensure Password Fields are Not Empty (Scored)
    shell: /bin/cat /etc/shadow | /bin/awk -F':' '($2 == "" ) { print $1 " does not have a password "}'
    register: result9_2_1
    changed_when: "result9_2_1.stdout"
    always_run: yes
    tags:
      - scored
      - section9.2
      - section9.2.1

  - name: 9.2.2 Verify No Legacy "+" Entries Exist in /etc/passwd File (Scored)
    shell: /bin/grep '^+:' /etc/passwd
    register: result9_2_2
    failed_when: result9_2_2.rc == 0
    changed_when: result9_2_2.rc == 0
    always_run: yes
    ignore_errors: yes
    tags:
      - scored
      - section9.2
      - section9.2.2

  - name: 9.2.3 Verify No Legacy "+" Entries Exist in /etc/shadow File (Scored)
    shell: /bin/grep '^+:' /etc/shadow
    register: result9_2_3
    failed_when: result9_2_3.rc == 0
    changed_when: result9_2_3.rc == 0
    always_run: yes
    ignore_errors: yes
    tags:
      - scored
      - section9.2
      - section9.2.3

  - name: 9.2.4 Verify No Legacy "+" Entries Exist in /etc/group File (Scored)
    shell: /bin/grep '^+:' /etc/group
    register: result9_2_4
    failed_when: result9_2_4.rc == 0
    changed_when: result9_2_4.rc == 0
    always_run: yes
    ignore_errors: yes
    tags:
      - scored
      - section9.2
      - section9.2.4

  - name: 9.2.5 Verify No UID 0 Accounts Exist Other Than root (Scored)
    shell: /bin/awk -F':' '($3 == 0) { print $1 }' /etc/passwd | grep -qx 'root'
    register: result9_2_5
    failed_when: result9_2_5.rc != 0
    changed_when: result9_2_5.rc != 0
    always_run: yes
    ignore_errors: yes
    tags:
      - scored
      - section9.2
      - section9.2.5

  - name: 9.2.6-9.2.20 Prep
    file: >
      path=/root/.ansible/9.2
      state=directory
    tags:
      - section9.2
      - section9.2.6
      - section9.2.7
      - section9.2.8
      - section9.2.9
      - section9.2.10
      - section9.2.11
      - section9.2.12
      - section9.2.13
      - section9.2.14
      - section9.2.15
      - section9.2.16
      - section9.2.17
      - section9.2.18
      - section9.2.19
      - section9.2.20

  - name: 9.2.6-9.2.20 Prep
    copy: >
      src="9.2/cis-{{item}}.sh"
      dest="/root/.ansible/9.2/cis-{{item}}.sh"
      mode=0700
      owner=root
      group=root
    with_items:
      - 9.2.6
      - 9.2.7
      - 9.2.8
      - 9.2.9
      - 9.2.10
      - 9.2.11
      - 9.2.12
      - 9.2.13
      - 9.2.14
      - 9.2.15
      - 9.2.16
      - 9.2.17
      - 9.2.18
      - 9.2.19
      - 9.2.20
    tags:
      - section9.2
      - section9.2.6
      - section9.2.7
      - section9.2.8
      - section9.2.9
      - section9.2.10
      - section9.2.11
      - section9.2.12
      - section9.2.13
      - section9.2.14
      - section9.2.15
      - section9.2.16
      - section9.2.17
      - section9.2.18
      - section9.2.19
      - section9.2.20

  - name: 9.2.6 Ensure root PATH Integrity (Scored)
    command: /root/.ansible/9.2/cis-9.2.6.sh
    tags:
      - scored
      - section9.2
      - section9.2.6

  - name: 9.2.7 Check Permissions on User Home Directories (Scored)
    command: /root/.ansible/9.2/cis-9.2.7.sh
    tags:
      - scored
      - section9.2
      - section9.2.7
 
  - name: 9.2.8 Check User Dot File Permissions (Scored)
    command: /root/.ansible/9.2/cis-9.2.8.sh
    tags:
      - scored
      - section9.2
      - section9.2.8

  - name: 9.2.9 Check Permissions on User .netrc Files (Scored)
    command: /root/.ansible/9.2/cis-9.2.9.sh
    tags:
      - scored
      - section9.2
      - section9.2.9

  - name: 9.2.10 Check for Presence of User .rhosts Files (Scored)
    command: /root/.ansible/9.2/cis-9.2.10.sh
    tags:
      - scored
      - section9.2
      - section9.2.10

  - name: 9.2.11 Check Groups in /etc/passwd (Scored)
    command: /root/.ansible/9.2/cis-9.2.11.sh
    tags:
      - scored
      - section9.2
      - section9.2.11

  - name: 9.2.12 Check That Users Are Assigned Valid Home Directories (Scored)
    command: /root/.ansible/9.2/cis-9.2.12.sh
    tags:
      - scored
      - section9.2
      - section9.2.12

  - name: 9.2.13 Check User Home Directory Ownership (Scored)
    command: /root/.ansible/9.2/cis-9.2.13.sh
    tags:
      - scored
      - section9.2
      - section9.2.13

  - name: 9.2.14 Check for Duplicate UIDs (Scored)
    command: /root/.ansible/9.2/cis-9.2.14.sh
    tags:
      - scored
      - section9.2
      - section9.2.14

  - name: 9.2.15 Check for Duplicate GIDs (Scored)
    command: /root/.ansible/9.2/cis-9.2.15.sh
    tags:
      - scored
      - check-only
      - section9.2
      - section9.2.15

  - name: 9.2.16 Check for Duplicate User Names (Scored)
    command: /root/.ansible/9.2/cis-9.2.16.sh
    tags:
      - scored
      - check-only
      - section9.2
      - section9.2.16

  - name: 9.2.17 Check for Duplicate Group Names (Scored)
    command: /root/.ansible/9.2/cis-9.2.17.sh
    tags:
      - scored
      - check-only
      - section9.2
      - section9.2.17

  - name: 9.2.18 Check for Presence of User .netrc Files (Scored)
    command: /root/.ansible/9.2/cis-9.2.18.sh
    tags:
      - scored
      - check-only
      - section9.2
      - section9.2.18

  - name: 9.2.19 Check for Presence of User .forward Files (Scored)
    command: /root/.ansible/9.2/cis-9.2.19.sh
    tags:
      - scored
      - check-only
      - section9.2
      - section9.2.19

  - name: 9.2.20 Check for Presence of User .forward Files (Scored)
    command: /root/.ansible/9.2/cis-9.2.20.sh
    tags:
      - scored
      - check-only
      - section9.2
      - section9.2.20

