---
#
# Copyright 2014 Major Hayden
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#

  - name: 5.4.1.1 Set Password Expiration Days (Scored)
    lineinfile: >
      backup=yes 
      state=present 
      dest=/etc/login.defs
      backrefs=yes
      regexp="^PASS_MAX_DAYS\s+"
      line="PASS_MAX_DAYS\t90"
    tags:
      - scored
      - section5.4
      - section5.4.1
      - section5.4.1.1

  - name: 5.4.1.2 Set Password Change Minimum Number of Days (Scored)
    lineinfile: >
      backup=yes 
      state=present 
      dest=/etc/login.defs
      backrefs=yes
      regexp="^PASS_MIN_DAYS\s+"
      line="PASS_MIN_DAYS\t7"
    tags:
      - scored
      - section5.4
      - section5.4.1
      - section5.4.1.2

  - name: 5.4.1.3 Set Password Expiring Warning Days (Scored)
    lineinfile: >
      backup=yes 
      state=present 
      dest=/etc/login.defs
      backrefs=yes
      regexp="^PASS_WARN_AGE\s+"
      line="PASS_WARN_AGE\t7"
    tags:
      - scored
      - section5.4
      - section5.4.1
      - section5.4.1.3

  - name: 5.4.1.4 Ensure inactive password lock is 30 days or less (Scored)
    command: "/usr/sbin/useradd -D -f 30"
    tags:
      - scored
      - section5.4
      - section5.4.1
      - section5.4.1.4


  - name: 5.4.2 Disable System Accounts (Scored) - preparation
    shell: awk -F':' '($3<1000 && $1!="root" && $1!="sync" && $1!="shutdown" && $1!="sync" && $1!="shutdown" && $1!="halt" && $7!="/sbin/nologin") { print $1 }' /etc/passwd
    register: enabled_system_accounts
    changed_when: false
    tags:
      - scored
      - section5.4
      - section5.4.2

  - name: 5.4.2 Disable System Accounts (Scored)
    command: /usr/sbin/usermod -s /sbin/nologin {{ item }}
    with_items: enabled_system_accounts.stdout_lines
    tags:
      - scored
      - section5.4
      - section5.4.2

  - name: 5.4.3 Set Default Group for root Account (Scored)
    user: >
      name=root
      group=root
    tags:
      - scored
      - section5.4
      - section5.4.3

  - name: 5.4.4 Set Default umask for Users (Scored)
    lineinfile: 
      state=present
      create=yes
      dest=/etc/profile.d/cis.sh
      line="umask 027"
    ignore_errors: true
    tags:
      - scored
      - section5.4
      - section5.4.4

  - name: 5.4.4 Ensure that /etc/profile.d/cis.sh has correct owner, group and mode (Scored)
    file: 
      path=/etc/profile.d/cis.sh 
      owner=root
      group=root
      mode=0644
    changed_when: false
    tags:
      - scored
      - section5.4
      - section5.4.4

