---
- name: 1.5.1 Restrict core dumps (Scored) - via pam
  lineinfile: >
    dest=/etc/security/limits.conf
    line="* hard core 0"
    insertafter=EOF
  tags:
    - scored
    - section1.5
    - section1.5.1

- name: 1.5.1 Restrict core dumps (Scored) - via sysctl
  sysctl: >
    name=fs.suid_dumpable
    value=0
    state=present
    ignoreerrors=yes
  tags:
    - scored
    - section1.5
    - section1.5.1

- name: 1.5.2 Configure ExecShield (Scored)
  sysctl: >
    name=kernel.exec-shield
    value=1
    state=present
    ignoreerrors=yes
  tags:
    - scored
    - section1.5
    - section1.5.2
  when: ansible_distribution_major_version == '6'

- name: 1.5.2 Ensure XD/NX support is enabled (Not Scored)
  shell: "dmesg | grep NX"
  tags:
    - section1.5
    - section1.5.2
  when: ansible_distribution_major_version == '7'

- name: 1.5.3 Enable Randomized Virtual Memory Region Placement (Scored)
  sysctl: >
    name=kernel.randomize_va_space
    value=2
    state=present
    ignoreerrors=yes
  tags:
    - scored
    - section1.5
    - section1.5.3

- name: 1.5.4 Ensure prelink is disabled (Scored)
  yum: >
    name=prelink
    state=removed
  tags:
    - scored
    - section1.5
    - section1.5.4

