---
  - name: 3.1.1 Disable IP Forwarding (Scored)
    sysctl:
      name=net.ipv4.ip_forward
      value=0
      state=present
      reload=yes
    when: ansible_distribution_major_version == '6'
    tags:
      - scored
      - section3.1
      - section3.1.1

  - name: 3.1.1 Disable IP Forwarding (Scored)
    sysctl:
      sysctl_file=/etc/sysctl.d/10-cis.conf
      name=net.ipv4.ip_forward
      value=0
      state=present
      reload=yes
    when: ansible_distribution_major_version == '7'
    tags:
      - scored
      - section3.1
      - section3.1.1

  - name: 3.1.2 Disable Send Packet Redirects (Scored)
    sysctl:
      name=net.ipv4.conf.all.send_redirects
      value=0
      state=present
      ignoreerrors=true
      reload=yes
    when: ansible_distribution_major_version == '6'
    tags:
      - scored
      - section3.1
      - section3.1.2

  - name: 3.1.2 Disable Send Packet Redirects (Scored)
    sysctl:
      sysctl_file=/etc/sysctl.d/10-cis.conf
      name=net.ipv4.conf.all.send_redirects
      value=0
      state=present
      ignoreerrors=true
      reload=yes
    when: ansible_distribution_major_version == '7'
    tags:
      - scored
      - section3.1
      - section3.1.2

  - name: 3.1.2 Disable Send Packet Redirects (Scored)
    sysctl:
      name=net.ipv4.conf.default.send_redirects
      value=0
      state=present
      ignoreerrors=true
      reload=yes
    when: ansible_distribution_major_version == '6'
    tags:
      - scored
      - section3.1
      - section3.1.2

  - name: 3.1.2 Disable Send Packet Redirects (Scored)
    sysctl:
      sysctl_file=/etc/sysctl.d/10-cis.conf
      name=net.ipv4.conf.default.send_redirects
      value=0
      state=present
      ignoreerrors=true
      reload=yes
    when: ansible_distribution_major_version == '7'
    tags:
      - scored
      - section3.1
      - section3.1.2
