---
- name: 2.1.1 Disable chargen-dgram (check if exists)
  stat: path=/etc/xinetd.d/chargen-dgram
  register: chargen_dgram
  tags:
    - scored
    - section2.1
    - section2.1.1

- name: 2.1.1 Disable chargen-dgram (disable xinetd service)
  service: >
      name=chargen-dgram
      state=stopped
      enabled=no
  when: chargen_dgram.stat.exists
  tags:
    - scored
    - section2.1
    - section2.1.1

- name: 2.1.1 Disable chargen-stream (check if exists) (Scored)
  stat: path=/etc/xinetd.d/chargen-stream
  register: chargen_stream
  tags:
    - scored
    - section2.1
    - section2.1.1

- name: 2.1.1 Disable chargen-stream (disable xinetd service) (Scored)
  service: >
      name=chargen-stream
      state=stopped
      enabled=no
  when: chargen_stream.stat.exists
  tags:
    - scored
    - section2.1
    - section2.1.1

- name: 2.1.2 Disable daytime-dgram (check if exists) (Scored)
  stat: path=/etc/xinetd.d/daytime-dgram
  register: daytime_dgram
  tags:
    - scored
    - section2.1
    - section2.1.2

- name: 2.1.2 Disable daytime-dgram (disable xinetd service) (Scored)
  service: >
      name=daytime-dgram
      state=stopped
      enabled=no
  when: daytime_dgram.stat.exists
  tags:
    - scored
    - section2.1
    - section2.1.2

- name: 2.1.2 Disable daytime-stream (check if exists) (Scored)
  stat: path=/etc/xinetd.d/daytime-stream
  register: daytime_stream
  tags:
    - scored
    - section2.1
    - section2.1.2

- name: 2.1.2 Disable daytime-stream (disable xinetd service) (Scored)
  service: >
      name=daytime-stream
      state=stopped
      enabled=no
  when: daytime_stream.stat.exists
  tags:
    - scored
    - section2.1
    - section2.1.2

- name: 2.1.3 Disable discard-dgram (check if exists) (Scored)
  stat: path=/etc/xinetd.d/discard-dgram
  register: discard_dgram
  tags:
    - scored
    - section2.1
    - section2.1.3

- name: 2.1.3 Disable discard-dgram (disable xinetd service) (Scored)
  service: >
      name=discard-dgram
      state=stopped
      enabled=no
  when: discard_dgram.stat.exists
  tags:
    - scored
    - section2.1
    - section2.1.3

- name: 2.1.3 Disable discard-stream (check if exists) (Scored)
  stat: path=/etc/xinetd.d/discard-stream
  register: discard_stream
  tags:
    - scored
    - section2.1
    - section2.1.3

- name: 2.1.3 Disable discard-stream (disable xinetd service) (Scored)
  service: >
      name=discard-stream
      state=stopped
      enabled=no
  when: discard_stream.stat.exists
  tags:
    - scored
    - section2.1
    - section2.1.3

- name: 2.1.4 Disable echo-dgram (check if exists) (Scored)
  stat: path=/etc/xinetd.d/echo-dgram
  register: echo_dgram
  tags:
    - scored
    - section2.1
    - section2.1.4

- name: 2.1.4 Disable echo-dgram (disable xinetd service) (Scored)
  service: >
      name=echo-dgram
      state=stopped
      enabled=no
  when: echo_dgram.stat.exists
  tags:
    - scored
    - section2.1
    - section2.1.4

- name: 2.1.4 Disable echo-stream (check if exists) (Scored)
  stat: path=/etc/xinetd.d/echo-stream
  register: echo_stream
  tags:
    - scored
    - section2.1
    - section2.1.4

- name: 2.1.4 Disable echo-stream (disable xinetd service) (Scored)
  service: >
      name=echo-stream
      state=stopped
      enabled=no
  when: echo_stream.stat.exists
  tags:
    - scored
    - section2.1
    - section2.1.4

- name: 2.1.5 Disable time-dgram (check if exists) (Scored)
  stat: path=/etc/xinetd.d/time-dgram
  register: time_dgram
  tags:
    - scored
    - section2.1
    - section2.1.5

- name: 2.1.5 Disable time-dgram (disable xinetd service) (Scored)
  service: >
      name=time-dgram
      state=stopped
      enabled=no
  when: time_dgram.stat.exists
  tags:
    - scored
    - section2.1
    - section2.1.5

- name: 2.1.5 Disable time-stream (check if exists) (Scored)
  stat: path=/etc/xinetd.d/time-stream
  register: time_stream
  tags:
    - scored
    - section2.1
    - section2.1.5

- name: 2.1.5 Disable time-stream (disable xinetd service) (Scored)
  service: >
      name=time-stream
      state=stopped
      enabled=no
  when: time_stream.stat.exists
  tags:
    - scored
    - section2.1
    - section2.1.5

- name: 2.1.6 Remove rsh-server (Scored)
  yum: >
    name=rsh-server
    state=absent
  tags:
    - scored
    - section2.1
    - section2.1.6

- name: 2.1.7 Remove talk-server (Scored)
  yum: >
    name=talk-server
    state=absent
  tags:
    - scored
    - section2.1
    - section2.1.7

- name: 2.1.8 Remove telnet-server (Scored)
  yum: >
    name=telnet-server
    state=absent
  tags:
    - scored
    - section2.1
    - section2.1.8

- name: 2.1.9 Remove tftp-server (Scored)
  yum: >
    name="{{item}}"
    state=absent
  with_items:
    - tftp-server
    - tftp
  tags:
    - scored
    - section2.1
    - section2.1.9

- name: 2.1.10 Ensure rsync service is not enabled (Scored)
  # NB. use service here not yum, because we want to keep the client
  service: >
    name=rsyncd
    state=stopped
    enabled=no
  tags:
    - scored
    - section2.1
    - section2.1.10

- name: 2.1.11 Remove xinetd (Scored)
  yum: >
    name=xinetd
    state=absent
  tags:
    - scored
    - section2.1
    - section2.1.11
