---
#
# Copyright 2014 Major Hayden
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#

  - name: 4.1.1.1 Configure Data Retention (Not Scored)
    lineinfile: >
      state=present
      dest=/etc/audit/auditd.conf
      regexp="^max_log_file ="
      line="max_log_file = {{ max_log_file }}"
    notify: Reload auditd Rules
    tags:
      - notscored
      - section4.1
      - section4.1.1

  - name: 4.1.1.2 Disable System on Audit Log Full (Scored)
    lineinfile: >
      state=present
      dest=/etc/audit/auditd.conf
      regexp="^space_left_action ="
      line="space_left_action = {{ space_left_action }}"
    notify: Reload auditd Rules
    tags:
      - scored
      - section4.1
      - section4.1.1
      - section4.1.1.2

  - name: 4.1.1.2 Disable System on Audit Log Full (Scored)
    lineinfile: >
      state=present
      dest=/etc/audit/auditd.conf
      regexp="^action_mail_acct ="
      line="action_mail_acct = {{ action_mail_acct }}"
    notify: Reload auditd Rules
    tags:
      - scored
      - section4.1
      - section4.1.1
      - section4.1.1.2

  - name: 4.1.1.2 Disable System on Audit Log Full (Scored)
    lineinfile: >
      state=present
      dest=/etc/audit/auditd.conf
      regexp="^admin_space_left_action ="
      line="admin_space_left_action = {{ admin_space_left_action }}"
    notify: Reload auditd Rules
    tags:
      - scored
      - section4.1
      - section4.1.1
      - section4.1.1.2

  - name: 4.1.1.3 Keep All Auditing Information (Scored)
    lineinfile: >
      state=present
      dest=/etc/audit/auditd.conf
      regexp="^max_log_file_action ="
      line="max_log_file_action = {{ max_log_file_action }}"
    notify: Reload auditd Rules
    tags:
      - scored
      - section4.1
      - section4.1.1
      - section4.1.1.3

  - name: 4.1.2 Enable auditd Service (Scored)
    service: >
      name=auditd
      enabled=yes
      state=running
    tags:
      - scored
      - section4.1
      - section4.1.2

  - name: 4.1.3 Enable Auditing for Processes That Start Prior to auditd (Scored)
    lineinfile: >
      state=present
      dest=/etc/grub.conf
      backrefs=yes
      regexp="(^\s*kernel.*)$(?<!audit=1)"
      line="\1 audit=1"
    tags:
      - scored
      - section4.1
      - section4.1.3
    when: ansible_distribution_major_version == '6'

  - name: 4.1.3 Enable Auditing for Processes That Start Prior to auditd (Scored) -- Make sure grub2 tools are installed
    yum: name=grub2-tools state=present
    tags:
      - scored
      - section4.1
      - section4.1.3
    when: ansible_distribution_major_version == '7'

  - name: 4.1.3 Enable Auditing for Processes That Start Prior to auditd (Scored)
    lineinfile:
      state=present
      dest=/etc/default/grub
      line='GRUB_CMDLINE_LINUX="audit=1 ${GRUB_CMDLINE_LINUX}"'
      insertafter=EOF
    tags:
      - scored
      - section4.1
      - section4.1.3
    when: ansible_distribution_major_version == '7'

  - name: 4.1.3 Enable Auditing for Processes That Start Prior to auditd (Scored) -- Run grub2-mkconfig after changes
    command: grub2-mkconfig -o /boot/grub2/grub.cfg
    tags:
      - scored
      - section4.1
      - section4.1.3
    when: ansible_distribution_major_version == '7'

  - name: 4.1.4 - 4.1.18 Configure auditd Rules (Scored)
    copy: >
      src=etc/audit/audit.rules
      dest=/etc/audit/audit.rules
    notify: Reload auditd Rules
    tags:
      - scored
      - section4.1
      - section4.1.4
      - section4.1.5
      - section4.1.6
      - section4.1.7
      - section4.1.8
      - section4.1.9
      - section4.1.10
      - section4.1.11
      - section4.1.12
      - section4.1.13
      - section4.1.14
      - section4.1.15
      - section4.1.16
      - section4.1.17
      - section4.1.18
