# https://bugzilla.redhat.com/show_bug.cgi?id=1026648
  - name: Reload auditd Rules
    shell: service auditd restart

  - name: Reload prelinking
    command: /usr/sbin/prelink -ua

  - name: Reload sshd
    service: name=sshd state=restarted
